name: Cifa Unit Test on Windows

on: [push, workflow_dispatch]

jobs:
  test-windows:
    runs-on: windows-latest
    defaults:
      run:
        shell: pwsh

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Setup MSVC
      uses: ilammy/msvc-dev-cmd@v1

    - name: Compile Unit Test
      run: |
        New-Item -ItemType Directory -Force build | Out-Null
        # 1) Build the standard library module IFC/OBJ.
        cl /std:c++latest /EHsc /nologo /W4 /utf-8 /c "$env:VCToolsInstallDir\modules\std.ixx" /ifcOutput build\std.ifc /Fo:build\std.obj
        # 2) Build and link unit test with std module reference.
        cl /std:c++latest /EHsc /nologo /W4 /utf-8 /I./ /Fe:build/cifa_unit_test.exe unit_test/cifa/cifa_unit_test.cpp Cifa.cpp /reference "std=build\std.ifc" build\std.obj

    - name: Run Cifa Unit Test
      run: |
        [Console]::OutputEncoding = [System.Text.Encoding]::UTF8

        ./build/cifa_unit_test.exe